//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _17codes.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class action
    {
        public int id { get; set; }
        public string actionName { get; set; }
        public string actionUrl { get; set; }
        public Nullable<int> actionSort { get; set; }
        public Nullable<System.DateTime> actionCreateTime { get; set; }
        public string actionImgUrl { get; set; }
        public Nullable<int> actionParent { get; set; }
        public string actionDes { get; set; }
    }
}
