//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _17codes.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string userAlias { get; set; }
        public string userAvatarUrl { get; set; }
        public string userAccount { get; set; }
        public string userPwd { get; set; }
        public string userSelfDes { get; set; }
        public string userSex { get; set; }
        public System.DateTime userBirth { get; set; }
        public string userPhone { get; set; }
        public string userName { get; set; }
        public string userEmail { get; set; }
        public string userSite { get; set; }
        public string userAddress { get; set; }
        public string userPosition { get; set; }
        public System.DateTime userCreateTime { get; set; }
        public string useLoginStats { get; set; }
        public string userHomeDown { get; set; }
        public string userFuns { get; set; }
        public string userFocus { get; set; }
    }
}
